baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "davidstrain.github.io" # the base hostname & protocol for your site.
title: "David Strain"


#paginate: 3 #articles per page
paginate_path: /notes/page:num #makes pagination working

gems: [jekyll-paginate]
paginate: 5
#paginate_path: "page:num"


#contacts
git: "https://github.com/davidstrain"  #Add your github url here.
stackoverflow: "http://stackoverflow.com/users/5025745/david" #Add your stackoverflow url here.
linkedin: "https://uk.linkedin.com/in/davidrjstrain"
twitter: ""

#disqus comment
disqus:
    shortname: "David" #replace with your disqus comment short name

#google analytics
google:
    tracking-id: "" #paste your tracking id here
#gems:
#  - jekyll-sitemap

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."
highlighter: pygments

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"
permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"


#markdown: kramdown

#kramdown:
#  input: GFM
#  syntax_highlighter: pygments
